### ISSUE TITLE
When the scan range is changed, point parasitic changes in the dynamic range appear.

### ISSUE THREAD

**Issue by YuryW** [jankae/LibreVNA#161] opened 2022-11-15 22:41 UTC
### LibreVNA Version

LibreVNA Version (64 bit): 1.5.0-alpha.1-a29c32355
OS: Windows 7 Version 6.1 (Build 7601: SP 1)
CPU Arch: x86_64

### Steps to reproduce

The application is launched with default settings.
The LibreVNA device is connected.
![1001](https://user-images.githubusercontent.com/79474615/202036632-775e9128-6d64-4ab1-a82d-04da3776d08b.jpg)
Change the number of points to 2001.
![1011](https://user-images.githubusercontent.com/79474615/202037058-a352e157-5c2d-418a-9f7b-4af92c54cea9.jpg)
Change the minimum scan frequency to 500 MHz.
![1021](https://user-images.githubusercontent.com/79474615/202037419-fa7dd325-34b9-4d32-a2cd-d24b66d99d93.jpg)
Clear parasitic bursts are visible on S21 (5 pieces) and S12 (so far 1 piece).
Now we change the upper scan frequency to 2.5 GHz.
![1031](https://user-images.githubusercontent.com/79474615/202038335-9531d952-1b3c-4143-88a5-515f3306d47e.jpg)
We already get more than 10 spurious points on S21.
Reduce the IF bandwidth to 200 Hz. Almost the same spurious emissions appear on S12.
![1051](https://user-images.githubusercontent.com/79474615/202038964-35c410c2-7542-4b94-88f2-3c27c98ada55.jpg)

### Expected behavior

Is it possible to get rid of these impulse pickups in the program settings? Or do you need to change something in the software?

### Extra information & Setup and Calibration files

No.

**Comment by jankae** [comment] 2022-11-16 08:56
Thanks for the report, I get very similar spikes (actually also on S12 before changing the IF to 200Hz). Interestingly, there is some difference between the VNA sweep and the manual control dialog. For example:
Zero span sweep at 1.111GHz (the location of a spike):
![image](https://user-images.githubusercontent.com/16818866/202133818-32d098e6-68fc-4560-abc0-16b4a3fabac9.png)
Signal level of about -66dB (similar to the spike).
The same settings with manual control:
![image](https://user-images.githubusercontent.com/16818866/202134025-cabd70bd-dc69-471d-801c-d495475b56d2.png)
Much better S21 result of about -100dB.

This will need some more debugging to determine the cause of the spike (most likely: aliasing of other frequencies into the ADC), I'll get back to you when I have more results.

**Comment by jankae** [comment] 2022-11-16 11:14
Some more info, at least I determined the cause of (most) spikes: It is 1.LO feedthrough mixed with harmonics of the 2.LO in the second stage mixer. Here with the example for the spike at 1.111GHz:
1.IF = 62 MHz -> 1.LO = 1173MHz
2.IF = 250kHz -> 2.LO = 61.75MHz -> 19th harmonic = 1173.25MHz

The second mixer now sees a 1173MHz input and also has some content on its LO at 1173.25MHz -> output 250kHz which the ADC interprets as a valid signal.

Unfortunately, there isn't really anything I can do in the software about that. Here are your possible work-arounds:
1. Shift your 1.LO or 2.LO in the preferences:
![image](https://user-images.githubusercontent.com/16818866/202164980-f56ab80d-1ac9-4db9-8593-d6325ef6b291.png)
This will not fix the problem but it will move the spikes to other frequencies. Could be a solution if you are only interested in a narrow frequency range and want to get rid of a spike in there.
2. Add a median filter to the traces. This will hide the spikes if they are narrow enough. But of course it would also hide actual narrow signals.
3. Add a lowpass to the 2.LO. The PCB already has the footprints for that but they are not populated:
![image](https://user-images.githubusercontent.com/16818866/202165465-e13db2b0-5959-42f6-a1e8-2f97b6b940bc.png)
![image](https://user-images.githubusercontent.com/16818866/202165582-146c1af6-4262-4f16-9294-9f496b33650f.png)

**Comment by jankae** [comment] 2022-11-16 11:24
> And even with an IF width of 10 kHz, once every few seconds in the very upper part of the range, a rather significant spurious impulse (burst) S21 and S12 slips through. (On IF 5 kHz and 20 kHz too, but less often).

Could that peak be at 5.928GHz? If so, please check that the following option is enabled: 
![image](https://user-images.githubusercontent.com/16818866/202167982-e30a6df0-ee59-4f09-8a95-1a7a64691da7.png)

**Comment by YuryW** [comment] 2022-11-16 14:50
Good afternoon Jankae. Thanks for the thorough answer.

> The second mixer now sees a 1173MHz input and also has some content on its LO at 1173.25MHz -> output 250kHz which the ADC interprets as a valid signal.

It turns out that the excessive broadband of the second mixer is to blame?

> 3\. Add a lowpass to the 2.LO. The PCB already has the footprints for that but they are not populated:

This option suits me the best. That is, LPF (3 pieces) at 62 MHz should practically solve this problem?


> Could that peak be at 5.928GHz? If so, please check that the following option is enabled:

Yes, this option is enabled. I set the marker mark to the frequency of 5.928 GHz: spurious bursts (once in a few tens of seconds or more often) both at this frequency and above it (quite wide sometimes).
![120](https://user-images.githubusercontent.com/79474615/202211150-13703421-b1e7-4861-b663-fbfbcb3156bf.jpg)
![122](https://user-images.githubusercontent.com/79474615/202211630-7341588a-45d6-4109-8cab-5b1030ad1d21.jpg)
![123](https://user-images.githubusercontent.com/79474615/202212124-dcff299a-1199-48e3-85da-48283c773a19.jpg)

**Comment by jankae** [comment] 2022-11-16 15:33
> This option suits me the best. That is, LPF (3 pieces) at 62 MHz should practically solve this problem? Is the location of these filters the same on a 6-layer LibreVNA board?

Yes, if that LPF attenuates the high harmonics of the 2.LO, it should also reduce the spike amplitude significantly (probably all the way to the noise floor for most frequencies). There could still be spikes with other causes but this should take care of most of them. The component location has not changed in the 6-layer board.

> I set the marker mark to the frequency of 5.928 GHz: spurious bursts (once in a few tens of seconds or more often) both at this frequency and above it (quite wide sometimes).

Unfortunately this is something that I can't replicate. I have added an option to show the raw data from the VNA receivers and would like to look at your raw data coming in. Could you please use the latest GUI and perform the following steps?
1. Enable raw data capturing in the preferences:
![image](https://user-images.githubusercontent.com/16818866/202222504-34dbe837-c631-4c91-8bd8-313a505c48e5.png)
After this, you will have eight additional live capture parameters available (RawPortXStageY[Ref]).
2. Create a new trace for each of these parameters (trace name isn't important, but you must select the correct parameter in the traces setup)
![image](https://user-images.githubusercontent.com/16818866/202222946-6002deca-095a-498d-aa4f-c27c15f5f446.png)
3. Stop the sweep when the peak is present
4. Export all eight raw data traces as .csv (with magnitude and phase) and attach that csv file

**Comment by YuryW** [comment] 2022-11-16 17:17
> 4\. Export all eight raw data traces as .csv (with magnitude and phase) and attach that csv file

![RawPortStage_1](https://user-images.githubusercontent.com/79474615/202247969-e69376c3-b685-435a-8ba9-8b5db50f4173.jpg)
[RawPortStage_1.csv](https://github.com/jankae/LibreVNA/files/10024154/RawPortStage_1.csv)
![RawPortStage](https://user-images.githubusercontent.com/79474615/202248488-d8fe347f-0aa6-4cfb-918a-b06a55feeb56.jpg)
[RawPortStage.csv](https://github.com/jankae/LibreVNA/files/10024158/RawPortStage.csv)

**Comment by jankae** [comment] 2022-11-16 20:44
Thank you very much for all the data. There is something in there that can explain the spike, although I still have no satisfying overall explanation: Your reference signal is almost completely missing for two frequency points. Without a reference signal, all receivers essentially only see noise and you get about 0dB for all S-parameters.
Here as an example in one of the raw data traces:
![image](https://user-images.githubusercontent.com/16818866/202288067-3f268265-574d-4fdb-8f03-bd1c56b37094.png)
Don't mind the large absolute dB values, what matters here is the drop of about 90dB at the frequencies of the spike. A bit of background on what happens if you enable "suppress invalid peaks":
- The 1.LO PLL has a limited frequency resolution, especially close to integer multiples of its reference frequency
- Depending on the frequency deviation and the selected IF bandwidth, the 2.IF might fall outside of the IF bandwidth, this would result in something like I am seeing in your raw data
- With "suppress invalid peaks" enabled, I calculate these problematic frequencies in the VNA and adjust the 2.LO to move the 2.IF back into the IF bandwidth

So far, I can think of two possible problems:
1. For some reason, this movement of the 2.LO does not happen for you. I think this is unlikely because it is entirely software based (and not a new feature, so it definitely is in the firmware you are running).
2. Changing the 2.LO requires a PLL reset in the Si5351c to align the phases of all 2.LO signals again. Maybe your copy of the chip takes longer for that to lock? I don't think that parameter is specified in the datasheet and I have based the waiting time on experimental results only. If that PLL fails to lock in time, your 2.LO is either completely missing or at the wrong frequency, which would also explain your measurement results. To test this theory, please try this firmware file: 
[LongerSettlingTimeFirmware.zip](https://github.com/jankae/LibreVNA/files/10025542/LongerSettlingTimeFirmware.zip)
It has an extended the settling time between changing the 2.LO and starting the sampling process.

**Comment by YuryW** [comment] 2022-11-16 21:45
> 2\. Чтобы проверить эту теорию, попробуйте этот файл прошивки: 
>     [LongerSettlingTimeFirmware.zip](https://github.com/jankae/LibreVNA/files/10025542/LongerSettlingTimeFirmware.zip)

Thank you Jankae. This firmware with increased time led to the desired result. In 4 minutes plus 15 minutes, no old outliers appeared at all. But in a strange way, after 4 minutes (device temperature 30 degrees C), the GUI crashed when the traces "froze". After clicking on Stop/Run, the following happened: after Run, there are no traces, but the mark readings changed within the same limits. And after Stop, the traces appeared in the stop mode.
![Drawing](https://user-images.githubusercontent.com/79474615/202299168-62e85fdf-47d7-4ae6-a196-cd2045dea518.jpg)
![Drawing_1](https://user-images.githubusercontent.com/79474615/202299238-7291f266-544e-453c-9171-1e9a55816bec.jpg)

After restarting the software, everything worked properly and has been running for 25 minutes without any complaints.

Perhaps my LibreVNA device behaves a little differently than the others, since its operating temperature does not usually exceed 40 degrees C (about 14 ... 15 degrees above ambient temperature). There are two large heatsinks on top and bottom of the device (no fan).

It looks like the 5.928 GHz spike issue has been resolved. At least for me with this firmware.

**Comment by jankae** [comment] 2022-11-16 21:52
Thanks for the confirmation, I'll merge the change into master soon. I will probably get back to you with another firmware to test at some point - I can't really test the change this my Si5351c seems to lock a lot faster than yours.

> the GUI crashed when the traces "froze"

This is likely unrelated but just to confirm: with "crash" you are just referring to the frozen/disappearing traces and the GUI keeps running? I now that there is some issue with the software there, I just can't track it down. But if you happen to find a way to replicate that problem, I'll try to fix it.

**Comment by YuryW** [comment] 2022-11-16 22:00
> But if you happen to find a way to replicate that problem, I'll try to fix it.

Thank you, if the problem of freezing appears, I will definitely let you know.
So far, she has been only once and has not appeared again (for half an hour of work, everything is fine).
Best regards.

**Comment by jankae** [comment] 2022-11-17 13:50
There is now a check for PLL lock before starting the sampling (instead of just waiting a predetermined amount of time). Please check if this version has no 5.928GHz spike with your device as well: https://github.com/jankae/LibreVNA/actions/runs/3488492187

**Comment by YuryW** [comment] 2022-11-17 18:55
> Please check if this version has no 5.928GHz spike with your device as well: https://github.com/jankae/LibreVNA/actions/runs/3488492187

Good evening Jankae. Tested this version of software and firmware:
LibreVNA Version (64 bit): 1.5.0-alpha.1-69b1d95ab
OS: Windows 7 Version 6.1 (Build 7601: SP 1)
CPU Arch: x86_64
The problem at 5.928GHz seems to be solved. There were no parasitic emissions found. But when testing harder 4001 points and 50 kHz IF, there were spikes at about 1 GHz, 2 GHz and a few more frequencies only on the S21! And for some reason, on S12 at IF 50 kHz, the noise level is much less, well, there are no parasitic bursts.
![RawPortStage_17_4001ps_20kHz](https://user-images.githubusercontent.com/79474615/202529540-92fb3e96-bdda-4c06-a8c1-8ab0694c7e4b.jpg)
[RawPortStage_17_4001ps_20kHz.csv](https://github.com/jankae/LibreVNA/files/10034555/RawPortStage_17_4001ps_20kHz.csv)
![RawPortStage_17_4001ps_50kHz_1](https://user-images.githubusercontent.com/79474615/202529708-3d50b438-82bd-417b-a6b9-b4f70b869c74.jpg)
[RawPortStage_17_4001ps_50kHz_1.csv](https://github.com/jankae/LibreVNA/files/10034556/RawPortStage_17_4001ps_50kHz_1.csv)
![RawPortStage_17_4001ps_50kHz_2](https://user-images.githubusercontent.com/79474615/202529835-7a5ac62b-56ce-483e-b992-1b129f8a7110.jpg)
[RawPortStage_17_4001ps_50kHz_2.csv](https://github.com/jankae/LibreVNA/files/10034566/RawPortStage_17_4001ps_50kHz_2.csv)
![RawPortStage_17_4001ps_50kHz_3](https://user-images.githubusercontent.com/79474615/202529930-2aa8e0b2-2fea-48dd-b2ec-995c70a5ad4e.jpg)
[RawPortStage_17_4001ps_50kHz_3.csv](https://github.com/jankae/LibreVNA/files/10034571/RawPortStage_17_4001ps_50kHz_3.csv)
![RawPortStage_17_4001ps_50kHz_4](https://user-images.githubusercontent.com/79474615/202530017-f5130691-e106-4640-841e-a2dca50a9935.jpg)
[RawPortStage_17_4001ps_50kHz_4.csv](https://github.com/jankae/LibreVNA/files/10034577/RawPortStage_17_4001ps_50kHz_4.csv)
![RawPortStage_17_4001ps_50kHz_5](https://user-images.githubusercontent.com/79474615/202530367-1f3e19fc-7d4d-4172-896e-389fa8d59c6a.jpg)
[RawPortStage_17_4001ps_50kHz_5.csv](https://github.com/jankae/LibreVNA/files/10034588/RawPortStage_17_4001ps_50kHz_5.csv)
And today, an attempt to check the box "Capture raw receiver values" led to the software freezing again. Something to do with the default calibration mismatch with the default settings. But it was not possible to repeat the situation, so there is no concrete data on this situation yet.

**Comment by YuryW** [comment] 2022-11-18 23:49
Perhaps this information will help:
![RawPortStage_19_4001ps_5_6GHz_30kHz](https://user-images.githubusercontent.com/79474615/202821067-2877fa19-6a16-494a-8681-36d7f35eed22.jpg)
[RawPortStage_19_4001ps_5_6GHz_30kHz.csv](https://github.com/jankae/LibreVNA/files/10045522/RawPortStage_19_4001ps_5_6GHz_30kHz.csv)
![RawPortStage_19_4001ps_5_6GHz_40kHz](https://user-images.githubusercontent.com/79474615/202821122-1176cde1-e45e-49c6-8a39-b85cc43bc46c.jpg)
[RawPortStage_19_4001ps_5_6GHz_40kHz.csv](https://github.com/jankae/LibreVNA/files/10045523/RawPortStage_19_4001ps_5_6GHz_40kHz.csv)
![RawPortStage_19_4001ps_5_6GHz_47kHz](https://user-images.githubusercontent.com/79474615/202821165-dc48e373-a774-441a-b1ad-ae121d13595c.jpg)
[RawPortStage_19_4001ps_5_6GHz_47kHz.csv](https://github.com/jankae/LibreVNA/files/10045525/RawPortStage_19_4001ps_5_6GHz_47kHz.csv)
![RawPortStage_19_4001ps_5_6GHz_48kHz](https://user-images.githubusercontent.com/79474615/202821205-e534026f-03e0-4eb0-8e28-8675edb8f05b.jpg)
[RawPortStage_19_4001ps_5_6GHz_48kHz.csv](https://github.com/jankae/LibreVNA/files/10045526/RawPortStage_19_4001ps_5_6GHz_48kHz.csv)
![RawPortStage_19_4001ps_5_6GHz_50kHz](https://user-images.githubusercontent.com/79474615/202821263-9d128c95-95ab-4139-98d8-b91bf4e70833.jpg)
[RawPortStage_19_4001ps_5_6GHz_50kHz.csv](https://github.com/jankae/LibreVNA/files/10045530/RawPortStage_19_4001ps_5_6GHz_50kHz.csv)
Best regards.

**Comment by jankae** [comment] 2022-11-19 15:33
Looks like another PLL issue to me. I could reproduce it but not with every copy of the LibreVNA I have. This time it is the MAX2871 PLL (for the source and the 1.LO). I already monitor the lock output and wait with sampling until the PLL claims to have locked (I actually wait for 20us after the lock has happened to allow for everything to settle).

Turns out that the MAX2871 sometimes keeps the lock output asserted when making a small frequency change. Maybe because the charge pump only needs to make a small adjustment? Not sure. But whatever the cause, I couldn't change the behavior with any of the registers that influence lock detect behavior.
The only thing I could come up with is increasing the settling time from 20us to 60us. This solved the issue for me but of course at the cost of reduced sweep speed. Please check if this helps in your case as well with [this](https://github.com/jankae/LibreVNA/actions/runs/3504081971) firmware.

By the way: you only get the spikes in S21 and S12 because they are sampled first. By the time S12 and S22 are sampled, the PLLs have properly locked.

**Comment by YuryW** [comment] 2022-11-19 19:42
> Please check if this helps in your case as well with [this](https://github.com/jankae/LibreVNA/actions/runs/3504081971) firmware.

Good evening Jankae. Yes, everything worked out. A new firmware is required. Only one updated software did not help, but with the new firmware everything is OK.
![19_4501ps_5 5GHz_6GHz_50kHz](https://user-images.githubusercontent.com/79474615/202868083-e7f314ff-a170-46c4-a015-fdf5a1f26118.jpg)
![19_4501ps_5GHz_6GHz_50kHz](https://user-images.githubusercontent.com/79474615/202868099-67ef172d-c75d-4923-95d4-3e8a13197160.jpg)
![19_4501ps_500MHz_2 5GHz_50kHz](https://user-images.githubusercontent.com/79474615/202868107-4e6c99f8-cc4a-48d8-8b4f-7c426f249f03.jpg)
I have the impression that sampling (its order) also affects the level of spurious emissions due to 2.LO harmonics.
![19_4501ps_500MHz_2 5GHz_200Hz](https://user-images.githubusercontent.com/79474615/202868239-b89fbebd-10ee-4d00-9d23-df781f501bc8.jpg)
In any case, until I put filters on 2.LO, you can deal with parasitic bursts by changing the number of points, as shown below:
![19_2001ps_500MHz_3GHz_200Hz](https://user-images.githubusercontent.com/79474615/202868377-4d151f5d-c88c-471a-bf39-a72bce85fe52.jpg)
![19_4501ps_500MHz_3GHz_200Hz](https://user-images.githubusercontent.com/79474615/202868387-fe98f4a3-a6a0-41f7-ae48-64e925a7a1e2.jpg)
Best regards.

**Comment by YuryW** [comment] 2022-11-19 23:06
Tried other edge cases. And here is the result.
![RawPortStage_20_4499ps_1MHz_6GHz_50Hz](https://user-images.githubusercontent.com/79474615/202874902-109c22f1-c929-46cb-acb3-61cec789b5f2.jpg)
[RawPortStage_20_4499ps_1MHz_6GHz_50Hz.csv](https://github.com/jankae/LibreVNA/files/10048093/RawPortStage_20_4499ps_1MHz_6GHz_50Hz.csv)
![RawPortStage_20_4499ps_1MHz_6GHz_10Hz](https://user-images.githubusercontent.com/79474615/202874914-421278f6-851f-420c-85f2-aafb37bfe214.jpg)
[RawPortStage_20_4499ps_1MHz_6GHz_10Hz.csv](https://github.com/jankae/LibreVNA/files/10048095/RawPortStage_20_4499ps_1MHz_6GHz_10Hz.csv)
As if at some point, the noise was inverted (instead of the bottom, it began to count up).

**Comment by jankae** [comment] 2022-11-19 23:25
> Tried other edge cases. And here is the result.

Yes, you have run into the limit of the "suppress invalid peaks" there. The frequencies at which the 2.LO needs to be shifted is calculated in advance and stored in a lookup table with 500 entries. With such low IF bandwidths and so many points, the 2.LO needs to be shifted more often than that and afterwards the peaks can no longer be suppressed. You should see corresponding warnings in the device log ("PLL deviation of 743Hz for measurement at 5997332592Hz, will cause a peak").
The easiest solution of just increasing the size of the lookup table is not possible due to the limited amount of RAM. I'll have to come up with something a bit more clever than that.

**Comment by YuryW** [comment] 2022-11-19 23:59
Yes, I found warnings. Example: "PLL deviation of 41Hz for measurement at 4142976222Hz, will cause a peak". Somehow I didn't look at the logs before.
As an option to programmatically, probably, limit the width of the IF for a certain number of points? For such a number of points, frequency range and 100 Hz IF, everything works normally.
![RawPortStage_20_4499ps_1MHz_6GHz_100Hz](https://user-images.githubusercontent.com/79474615/202876060-693a2a97-b586-4d73-bf52-05514af8272e.jpg)

**Comment by jankae** [comment] 2022-11-20 00:24
I think I found a cleaner solution: get rid of the lookup table altogether and calculate the required shifts of the 2.LO right when they are needed. When I initially implemented the lookup table I thought it would save time but when shifting the 2.LO I have to wait for it to lock anyway. Any additional calculation before that isn't really that critical.

Another firmware to test: https://github.com/jankae/LibreVNA/actions/runs/3505746388 (no changes to the GUI, updating the firmware is enough)

By the way: thanks a lot for all the extensive tests/screenshots/data :)

**Comment by YuryW** [comment] 2022-11-20 06:22
> Another firmware to test: https://github.com/jankae/LibreVNA/actions/runs/3505746388 (no changes to the GUI, updating the firmware is enough)

It just worked out great. Thank you very much. There are small incomprehensibility for me (jumps in phase and amplitude). Circled them. Perhaps this is not important, but just in case, and suddenly it will help, if anything. I think that we can now safely close the issue.
![RawPortStage_20_4499ps_1MHz_6GHz_10Hz_new_1](https://user-images.githubusercontent.com/79474615/202888646-e47a2051-6b80-4017-8735-d2fa6edfcad6.jpg)
[RawPortStage_20_4499ps_1MHz_6GHz_10Hz_new.csv](https://github.com/jankae/LibreVNA/files/10048980/RawPortStage_20_4499ps_1MHz_6GHz_10Hz_new.csv)
![RawPortStage_20_4499ps_5GHz_6GHz_10Hz_new](https://user-images.githubusercontent.com/79474615/202888665-6c64c460-f2f6-42e9-8a02-83e50a28f723.jpg)
[RawPortStage_20_4499ps_5GHz_6GHz_10Hz_new.csv](https://github.com/jankae/LibreVNA/files/10048981/RawPortStage_20_4499ps_5GHz_6GHz_10Hz_new.csv)
![20_4499ps_5GHz_6GHz_50kHz_new](https://user-images.githubusercontent.com/79474615/202888681-1c6f2a79-c395-4dbb-a492-6a9df93fc63a.jpg)
![20_4499ps_500MHz_2 5GHz_50Hz_new](https://user-images.githubusercontent.com/79474615/202888690-212fdfa4-8720-4b91-b425-f14991c2af30.jpg)
Best regards.

**Comment by jankae** [comment] 2022-11-20 17:58
> But with this firmware, what are the restrictions on the number of points now?

Still the 4501 point limit (limited by the amount of RAM in the FPGA). But the GUI already includes a segmented sweep option which automatically splits the sweep into multiple smaller sweeps (on the hardware level). This is completely transparent for the user, the only thing you might notice is a short pause in the sweep when the next segment is set up in the hardware. With this feature enabled, the point limit is 65535 (and could also be increased but I don't think anyone needs more than that).

> I think that we can now safely close the issue.

Okay, I'll go ahead and close this.

**Closed by jankae** 2022-11-20 17:58 UTC

**Comment by YuryW** [comment] 2023-01-05 18:49
> Some more info, at least I determined the cause of (most) spikes: It is 1.LO feedthrough mixed with harmonics of the 2.LO in the second stage mixer. Here with the example for the spike at 1.111GHz: 1.IF = 62 MHz -> 1.LO = 1173MHz 2.IF = 250kHz -> 2.LO = 61.75MHz -> 19th harmonic = 1173.25MHz
> 
> The second mixer now sees a 1173MHz input and also has some content on its LO at 1173.25MHz -> output 250kHz which the ADC interprets as a valid signal.
> 
> Unfortunately, there isn't really anything I can do in the software about that. Here are your possible work-arounds:
> 
> 1. Shift your 1.LO or 2.LO in the preferences:
>    ![image](https://user-images.githubusercontent.com/16818866/202164980-f56ab80d-1ac9-4db9-8593-d6325ef6b291.png)
>    This will not fix the problem but it will move the spikes to other frequencies. Could be a solution if you are only interested in a narrow frequency range and want to get rid of a spike in there.
> 2. Add a median filter to the traces. This will hide the spikes if they are narrow enough. But of course it would also hide actual narrow signals.
> 3. Add a lowpass to the 2.LO. The PCB already has the footprints for that but they are not populated:
>    ![image](https://user-images.githubusercontent.com/16818866/202165465-e13db2b0-5959-42f6-a1e8-2f97b6b940bc.png)
>    ![image](https://user-images.githubusercontent.com/16818866/202165582-146c1af6-4262-4f16-9294-9f496b33650f.png)

Hi Jankae,
Designed the LP filter for 2.LO based on the PCB layout of 6 layers of LibreVNA. Used QucsStudio. In my opinion, I used QucsStudio to the maximum in order to take into account all the parasitic elements that distinguish the filter from the ideal one in this frequency range (it is in the upper right corner of the diagram). The 5.1 pF capacitor improves the dynamic range at 6 GHz by about 10 dB (until I started using it). Capacitors must be in parallel of two of a smaller value, and not one of a larger one, so that filtering (dynamic range) is better according to QucsStudio.

![LPF_62MHz_QucsStudio](https://user-images.githubusercontent.com/79474615/210851294-fb82e0e4-9b4a-4eb6-ad97-78ed0f76acad.jpg)

Who wants to repeat this filter - pay attention to the marking of the applied capacitors and inductances from Murata. With other capacitors and inductors, the frequency response will be different.
All harmonics above 700 MHz are filtered better than 100 dB.
Here are the manifestations of harmonics of the local oscillator without a 62 MHz filter (see above (earlier) in the text of this problem.

![Old_without_filtr_2 LO](https://user-images.githubusercontent.com/79474615/210853392-ce521bb9-092e-41b5-9c0c-647e831b62ea.jpg)

And here are new measurements with similar old settings already with LPF 62 MHz applied. At S21, part of the parasitic bursts noticeably decreased, especially above 1.2 GHz, but at IF 1 kHz at S12, their number seems to have increased. In theory, these bursts should no longer be above 700 MHz.

![New_with_filtr_2 LO](https://user-images.githubusercontent.com/79474615/210855392-b09d1f81-ab5e-485e-8815-a7e380b3df45.jpg)

![New_with_filtr_2 LO_IF_200Hzя](https://user-images.githubusercontent.com/79474615/210855588-4ad103d9-5032-4a03-8df1-56f3175c29a7.jpg)

**Comment by YuryW** [comment] 2023-01-05 18:57
> The second mixer now sees a 1173MHz input

If Jankae doesn't mind, then here or (probably better there) on the forum, I will later consider the pros and cons of other filters that come after the first and second mixer using QucsStudio.
Best regards.

**Comment by YuryW** [comment] 2023-01-08 11:31
I will offer an easy to remember way to solve the problem, when in such a case - the initial data: VNA, Start frequency 500 MHz, end frequency 2.5 GHz, number of points 2001, IF bandwidth 100 Hz, spikes appear, as in the picture below:

![VNA_1 5GHz_Span_2GHz_Points_2001_IF_100Hz](https://user-images.githubusercontent.com/79474615/211193227-b11b4979-231c-427d-9477-165a0254fb58.jpg)

You need to shift the initial scan frequency of the VNA up or down by 250 kHz (IF2). In the vast majority of cases, such a change is acceptable for measurements and is practically not noticeable. But there is an effect:

![VNA_1 50012GHz_Span_1 99975GHz_Points_2001_IF_100Hz](https://user-images.githubusercontent.com/79474615/211193450-6e8c96ce-607e-45ba-a2ed-4dcd2d34c74f.jpg)
![VNA_1 49988GHz_Span_2 00025GHz_Points_2001_IF_100Hz](https://user-images.githubusercontent.com/79474615/211193479-61b63bef-54cf-4fb3-b48a-6650c44f1a15.jpg)

Whether this always works will be shown by the experience of dear readers of the topics discussed here on LibreVNA (a wonderful assistant for amateurs and radio professionals).
Post your results here.

**Comment by YuryW** [comment] 2023-01-10 14:01
VNA mode: start frequency 1 MHz, stop frequency 6 MHz - there are bursts.

![Dynamic_range_bursts](https://user-images.githubusercontent.com/79474615/211569534-0ad93282-9540-460d-8f18-2107910f54aa.jpg)

VNA mode: start frequency 1.25 MHz (750kHz), stop frequency 6 MHz - no bursts.

![Dynamic_range_bursts_1](https://user-images.githubusercontent.com/79474615/211569618-81c5a2a9-94a1-4fe7-8472-f10a9f0c5e13.jpg)
![Dynamic_range_bursts_2](https://user-images.githubusercontent.com/79474615/211570933-0754ee70-8faa-4526-b462-3bd40249d8c1.jpg)
