### ISSUE TITLE
Axis Setup->X axis Power - Default max is 6 GdBm. Trimming the level label in the lower left corner on the left and right.

### ISSUE THREAD

**Issue by YuryW** [jankae/LibreVNA#155] opened 2022-10-22 05:32 UTC
### LibreVNA Version

LibreVNA Version (64 bit): 1.5.0-alpha.1-796a8cb3f
OS: Windows 7 Version 6.1 (Build 7601: SP 1)
CPU Arch: x86_64

### Steps to reproduce

LbbreVNA application is running. The device is not connected.
Trace Display Area ->XY-plot->Axis Setup->X axis Power - Default max is 6 GdBm. Trimming the level label in the lower left corner on the left and right.
![Power_axis - copy](https://user-images.githubusercontent.com/79474615/197322113-760e2497-c797-481c-addb-087052f9eaa9.jpg)
And also here. Axis setup -> X axis : after switching from Frequency (Power) to Time or Distance, you cannot switch back to Freqency (Power) without exiting this (Axis Setup) menu and re-entering.

### Expected behavior

Probably the default X-axis Power should be Minimum -40 dBm, Maximum 0 dBm. Or something close to the characteristics of the device.
Or rather, as specified in Preferences -> Power Sweep : -30 dBm...-10dBm.

### Extra information & Setup and Calibration files

No.

### Confirming that you haven´t forgot to include configuration files (if applicable)

- [ ] Setup file
- [ ] Calibration file
- [ ] Touchstone file of measurements

**Comment by jankae** [comment] 2022-10-25 11:22
Okay, several small things in this issue:

> Trace Display Area ->XY-plot->Axis Setup->X axis Power - Default max is 6 GdBm

- While in the axis setup dialog, no autoranging is performed. The selected settings are only applied once you close the dialog. This means that you will still see the old min/max values when switching from one X axis type to the other, even when autoranging is active
- When the x axis is displaying power, autoranging only supports the "fit traces" mode
- In your example there are no traces (or at least no traces with datapoints), so autoranging doesn't know what to do and just leaves the minimum/maximum as it was
- If you now add a trace, autoranging should work as intended and adjust your X axis settings

I have now improved this slightly. In case autoranging doesn't find any traces, it uses default min/max values instead of just leaving them as they are. The default min/max values depend on the X axis type (frequency/power). If a device is connected, its maximum/minimum supported values are used as the limits. If no device is connected, some hardcoded default values are used instead.

> Trimming the level label in the lower left corner on the left and right.

This bug was recently introduced when fixing some display issues for larger font sizes. Should be fixed now.

> Axis setup -> X axis : after switching from Frequency (Power) to Time or Distance, you cannot switch back to Freqency (Power) without exiting this (Axis Setup) menu and re-entering.

This one I can't replicate. I can switch between any X axis settings for any number of times without closing the dialog inbetween.

**Comment by YuryW** [comment] 2022-10-25 14:08
> In case autoranging doesn't find any traces, it uses default min/max values instead of just leaving them as they are.

Now in LibreVNA Version (64 bit): 1.5.0-alpha.1-2dd4edfae
a little wrong. When switching X axis to Power with no device connected, the X range is set to -100dBm ... 30dBm. And in Sweep type Power the default is -30dBm...-10dBm. That is, these settings are not synchronized?
![X_axis_Power](https://user-images.githubusercontent.com/79474615/197791692-9ed76921-bb3b-41df-bf3a-bf3314d0e683.jpg)

**Comment by jankae** [comment] 2022-10-25 14:11
> That is, these settings are not synchronized?

No, they are not. They would be for autorange mode "use span", but I haven't implemented that yet for the X axis in power mode.

What you are getting are the default values when no device is connected.

**Comment by YuryW** [comment] 2022-10-25 14:22
> This one I can't replicate.
We switch in X axis from Frequency to Time, then again to Frequency. Here's what I have with the charts...
The frequency graph will already be different.
![X_axis_Time](https://user-images.githubusercontent.com/79474615/197798992-fc437b39-d8bc-449c-a194-2a5ce908e957.jpg)
![X_axis_Time-1](https://user-images.githubusercontent.com/79474615/197799115-18030852-3ddb-4f24-8f7d-c13bfc4a70ed.jpg)
![X_axis_Time-2](https://user-images.githubusercontent.com/79474615/197799211-3bdf5319-5995-4ca1-890b-7c8ce39d333a.jpg)
![X_axis_Time-3](https://user-images.githubusercontent.com/79474615/197799293-ce2abe80-c638-4dda-a999-f4316b43ff23.jpg)

**Comment by YuryW** [comment] 2022-10-25 14:31
> > That is, these settings are not synchronized?
> 
> No, they are not. They would be for autorange mode "use span", but I haven't implemented that yet for the X axis in power mode.
> 
> What you are getting are the default values when no device is connected.

Thanks Jankae. It's clear.

**Comment by jankae** [comment] 2022-10-25 14:37
> We switch in X axis from Frequency to Time, then again to Frequency. Here's what I have with the charts...
The frequency graph will already be different.

The switch from frequency to time disables the Y axes, because the previously selected axis types are not available in the time domain. When you switch back to frequency, they are still disabled (the software doesn't store the previously selected type). If you select magnitude (for the primary Y axis) and phase (for the secondary Y axis), you should get the original frequency graph back.

**Comment by YuryW** [comment] 2022-10-25 14:49
It's clear. And here too, Jankey. Maybe when switching Sweep Frequency to Sweep Power, or change graphics to other ones automatically, or not change the frequency on the remaining graphs?
![Sweep_type_Freqency](https://user-images.githubusercontent.com/79474615/197806511-ef8746d2-ecce-431b-af78-f044e8929d43.jpg)
![Sweep_type_Power](https://user-images.githubusercontent.com/79474615/197806580-566252e4-609c-48c5-bcab-0c7a1572867a.jpg)

**Comment by jankae** [comment] 2022-10-25 14:55
Ah, I haven't tested that specific case. The graphs can switch the axis type automatically, if the trace data changes. It only works halfway for you, because your traces are empty (no device connected). If you have incoming data, the graphs would have switched to power. You can control the behavior in the settings:
![grafik](https://user-images.githubusercontent.com/16818866/197808097-82a05ef2-f4d4-48d6-924b-75b5ba863045.png)

**Comment by YuryW** [comment] 2022-10-25 14:59
It's clear. A lot of the behavior of the application depends on whether the device is connected...
Let's close these questions then...

**Comment by jankae** [comment] 2022-10-25 15:11
I'll increase tests without the device connected in the future. Your case is also special because the only cases you have on the graphs are empty. If they would contain some points (e.g. imported from a touchstone file), the graph behavior would probably be a bit more intuitive.

**Closed by jankae** 2022-10-25 15:11 UTC
